version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            virtualenv /tmp/venv
            . /tmp/venv/bin/activate
            pip install -e .
            pip install ./[dev]

      - save_cache:
          paths:
            - /tmp/venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            . /tmp/venv/bin/activate
            nosetests
